INSERT INTO tags (name) VALUES
('Bicentenario'),
('Independencia'),
('Patrimonio cultural'),
('Tradiciones bolivianas'),
('Colonización'),
('Movimientos sociales'),
('Luchas campesinas'),
('Exilio'),
('Revolución de 1952'),
('Resistencia indígena'),
('Mestizaje'),
('Folklore'),
('Fiestas tradicionales'),
('Indígenas'),
('Afrobolivianos'),
('Migrantes'),
('Pueblos originarios'),
('Desplazados'),
('Mujeres en Bolivia'),
('Jóvenes'),
('Vivienda rural'),
('Educación'),
('Justicia social'),
('Derechos humanos'),
('Testimonio de vida'),
('Historia de familia'),
('Historia personal'),
('Memoria colectiva'),
('Experiencia de guerra'),
('Relato de exilio'),
('Recuerdos de infancia'),
('Testimonio de pobreza'),
('Cambio social'),
('Luchas políticas'),
('Esperanza'),
('Superación'),
('Resiliencia'),
('Desafíos'),
('Lucha por la justicia'),
('Dificultades'),
('Reconstrucción'),
('Sueños'),
('Memoria histórica'),
('Trauma'),
('Orgullo');