create table posts (
    id_post bigserial,
    id_user bigserial not null,
    title varchar(300) not null,
    description varchar(800) not null,
    stars numeric(6,1) default 0,
    views bigint default 0,
    likes int default 0,
    dislikes int default 0,
    id_city int not null,
    type numeric(1,0),
    id_file int,
    content text,
    is_published boolean default false,
    id_curator bigint,
    id_status int not null,
    id_head int,
    id_child int,
    id_event bigint,
    is_deleted boolean default false,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    primary key (id_post),
    Foreign Key (id_user) REFERENCES users(id_user) on delete cascade,
    Foreign Key (id_city) REFERENCES cities(id_city) on delete cascade,
    Foreign Key (id_file) REFERENCES files(id_file) on delete cascade,
    Foreign Key (id_status) REFERENCES post_statuses(id_status) on delete cascade,
    Foreign Key (id_curator) REFERENCES users(id_user) on delete cascade,
    Foreign Key (id_event) REFERENCES events(id_event) on delete cascade
);